export const experienceData = [
  {
    title: "Associate Software Engineer - KoderLabs",
    duration: "June 2025 - Present",
    description: [
      "Developed scalable, high-performance mobile applications using React Native and web applications using React and Next.js.",
      "Integrated RESTful APIs to deliver dynamic, real-time features across mobile and web platforms.",
      "Implemented location-based features using Google Maps APIs.",
      "Built responsive, SEO-friendly UIs with Next.js, TypeScript, and Tailwind CSS.",
      "Ensured cross-platform compatibility and performance optimization for Android, iOS, and web.",
      "Wrote reusable components and managed application state using Zustand.",
      "Collaborated with backend teams on API design, integration, and optimization.",
      "Actively participated in bug fixing, R&D, and code reviews while following industry best practices.",
    ],
    tech: [
      "React.js",
      "React Native",
      "TypeScript",
      "Zustand",
      "React Query",
      "Next.js",
      "Tailwind CSS",
      "Api Integration",
      "Git",
      "GitHub",
    ],
  },
  {
    title: "Associate Software Engineer - Native Brains",
    duration: "Feb 2024 - May 2024",
    description: [
      "Translated wireframes into functional and responsive front-end code, contributing to a seamless user experience and efficient project development.",
      "Collaborated closely with backend developers and designers, ensuring smooth integration of design elements and APIs to meet project requirements and deadlines.",
      "Followed best coding practices, including clean and maintainable code, and integrated RESTful APIs and services, which enhanced the overall project performance and scalability.",
    ],
    tech: [
      "React.js",
      "TypeScript",
      "Tailwind CSS",
      "Ant Design",
      "Api Integration",
      "VS Code",
      "Git",
      "GitHub",
    ],
  },
];
